spring:
  application:
    name: institution-service
  # La configuration de base de Consul est déjà définie dans bootstrap.yml
#  cloud:
#    consul:
#      discovery:
#        enabled: ${CONSUL_DISCOVERY_ENABLED:false}  # Désactivé par défaut en local

  data:
    mongodb:
      uri: mongodb://localhost:27017/payiskoul_institutions
      auto-index-creation: true
      # Configuration pour le développement local
      connection-pool-size: 10
      connect-timeout: 5000
      socket-timeout: 5000

  redis:
    host: localhost
    port: 6379
    timeout: 10000
    connect-timeout: 10000
    # Configuration pour le développement local
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # Configuration pour le développement local
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 1.5
        acknowledge-mode: auto
        prefetch: 1
        default-requeue-rejected: false

  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 heure
      cache-null-values: false
      key-prefix: "instsvc_local:"

